[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "elf2uf2-rs -d"

[build]
target = "thumbv6m-none-eabi"

# [env]
# DEFMT_LOG = "debug"

# deals with type AtomicUsize issue
[patch.crates-io]
delog = {git = "https://github.com/LechevSpace/delog.git", rev = "869167f7ff0630518c86f30afd215fee124d19c1"}
