[workspace]
resolver = "2"

members = [
    # where the magic happens
    "engine", 
    # httpd implementation for std environment
    "lib_httpd", 

    # engines
    "engine_race",
    "engine_tune",

    # apps
    "nano-sketch",
    "std_httpd",

    "rpi",
]