[workspace]
resolver = "2"

members = [
    # where the magic happens
    "engine", 
    # httpd implementation for std environment
    "lib_httpd", 
    "engine_race",

    # apps
    "nano-sketch",
    "std_httpd",
    "rpi",
]