[workspace]
resolver = "2"

members = [
    # where the magic happens
    "engine", 
    # httpd implementation for std environment
    "lib_httpd", 

    # engines
    "engine_race",
    "engine_tune",

    # apps
    "nano-sketch",
    "std_httpd",

    "rpi",
]

[patch.crates-io]
delog = {git = "https://github.com/LechevSpace/delog.git", rev = "869167f7ff0630518c86f30afd215fee124d19c1"}
