[package]
edition = "2021"
name = "rpi"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[dependencies]
embassy-embedded-hal = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy", features = [
    "defmt",
] }
embassy-futures = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy" }
embedded-hal-1 = { package = "embedded-hal", version = "=1.0.0-rc.1" }
embedded-hal-async = "1.0.0-rc.1"

embassy-usb-logger = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy" }
defmt = "0.3"
defmt-rtt = "0.4"
fixed = "1.23.1"
fixed-macro = "1.2"

embassy-executor = { version = "0.3.0", git = "https://github.com/embassy-rs/embassy", features = [
    "defmt",
    "nightly",
    "arch-cortex-m",
    "executor-thread",
    "executor-interrupt",
    "integrated-timers",
] }
embassy-time = { version = "0.1.3", git = "https://github.com/embassy-rs/embassy", features = [
    "defmt",
    "nightly",
    "unstable-traits",
] }
embassy-rp = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy", features = [
    "defmt",
    "unstable-traits",
    "nightly",
    "unstable-pac",
    "time-driver",
    "critical-section-impl",
] }
embassy-net = { version = "0.2.0", git = "https://github.com/embassy-rs/embassy", features = [
    "defmt",
    "nightly",
    "tcp",
    "udp",
    "dhcpv4",
    "medium-ethernet",
] }

embassy-sync = { version = "0.3.0", git = "https://github.com/embassy-rs/embassy", features = [
    "defmt",
    "nightly",
] }


cyw43 = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy", features = [
    "firmware-logs",
] }
cyw43-pio = { version = "0.1.0", git = "https://github.com/embassy-rs/embassy", features = [
    "overclock",
] }

cortex-m = { version = "0.7.6", features = ["inline-asm"] }
cortex-m-rt = "0.7.0"
panic-probe = { version = "0.3", features = ["print-defmt"] }
heapless = "0.7.15"

embedded-io-async = { version = "0.6.0", features = ["defmt-03"] }
static_cell = { version = "1.1", features = ["nightly"] }
log = "0.4"

portable-atomic = { version = "0.3", default-features = false }


lib_httpd = { path = "../lib_httpd/" }
engine_race = { path = "../engine_race/" }


[profile.release]
debug = 2
