[package]
name = "tgt-std"
version = "0.1.0"
edition.workspace = true
license = "MIT OR Apache-2.0"

[dependencies]
# Common crate for shared code
common = { path = "../common", features = ["std"] }

embassy-executor = { workspace = true, features = ["executor-thread", "platform-std"] }
embassy-time = { workspace = true, features = ["std"] }
critical-section = { version = "1.2", features = ["std"] }

edge-http = { workspace = true, features = ["std"] }
edge-nal = { workspace = true }
edge-nal-std = { workspace = true }

log = { workspace = true }

# required by extreme_traits::define_engines!
heapless = { workspace = true }
serde = { workspace = true }
serde-json-core = { workspace = true, features = ["heapless"] }
static_cell = { workspace = true }

#
# The magic
#
extreme-traits = { path = "../extreme-traits/" }
extreme-race = { path = "../extreme-race/" }
extreme-tune = { path = "../extreme-tune/" }
