[package]
name = "nano_lib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.release]
lto = true

[build]
target = "thumbv6m-none-eabi"
# target = "thumbv7em-none-eabihf"

[dependencies]
httparse = { version = "1", default-features = false }
cty = "0.2.2"
