[package]
name = "extreme-tune"
version = "0.1.0"
edition.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
serde = { workspace = true }
libm = { workspace = true }
heapless = { workspace = true }
serde-json-core = { workspace = true }

extreme-traits = { path = "../extreme-traits" }

[dev-dependencies]
serde_json = { workspace = true }
